#!/bin/bash

#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>

/*Check if a number is prime*/
bool is_prime(int n)
{
	if (n <= 1)
	{
        return false;
	}
	for (int i = 2; i * i <= n; i++)
	{
        	if (n % i == 0)
		{
            		return false;
        	}
    	}
    	return true;
}

// Find two factors of a number
void factorize(int n, int* p, int* q)
{
    	for (int i = 2; i <= n / 2; i++)
	{
        	if (n % i == 0)
		{
            		*p = i;
            		*q = n / i;
			return;
		}
	}
}

/*main function*/


int main(int argc, char* argv[])
{
    	if (argc < 2)
	{
        printf("Usage: factors <file>\n");
        return 1;
    	}
    	FILE* fp = fopen(argv[1], "r");
   	if (fp == NULL)
	{
        	printf("Error: Cannot open file %s\n", argv[1]);
        	return 1;
    	}
    	int n;
    	while (fscanf(fp, "%d\n", &n) != EOF)
	{
        	int p, q;
        	factorize(n, &p, &q);
        	printf("%d=%d*%d\n", n, p, q);
    	}
    	fclose(fp);
    	return 0;
}
