#!/usr/bin/python3

import math
import sys

def pollard_rho(n):
    if n % 2 == 0:
        return 2
    
    x = 2
    y = 2
    d = 1

    f = lambda x: (x**2 + 1) % n

    while d == 1:
        x = f(x)
        y = f(f(y))
        d = math.gcd(abs(x - y), n)
    
    return d

def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(math.sqrt(num)) + 1):
        if num % i == 0:
            return False
    return True

def main():
    if len(sys.argv) != 2:
        print("Usage: python factorize.py <file>")
        return

    file_path = sys.argv[1]

    try:
        with open(file_path, 'r') as file:
            number = int(file.readline().strip())
        
        factor = pollard_rho(number)
        
        while not is_prime(factor):
            factor = pollard_rho(factor)
        
        if factor == number:
            print(f"{number} is prime.")
        else:
            print(f"{number}={number // factor}*{number}")
    
    except FileNotFoundError:
        print(f"File '{file_path}' not found.")

if __name__ == '__main__':
    main()

